name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable pnpm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Create Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changesets tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
